### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by Gnanendra18** [material-foundation/material-remixer-remote-web#10]
After building and deploying into firebase, I am getting around 8 files in public folder. but when I am accessing the url it is not showing anything. When I checked in console it is throwing error in console 
main.js:52 Uncaught ReferenceError: $ is not defined
    at main.js:52

Please guide me what steps to be performed.

**Comment by chriscox** [comment]
Hello, let's first confirm the steps you followed to make sure everything is properly set up.

Can you confirm you've done each the following:

1. Check out this repo.
2. Run `npm install` at root of directory.
3. Sign up for Firebase, or get existing project credentials. You will need to get your Project ID from Firebase. Follow guidelines [here](https://support.google.com/cloud/answer/6158840?hl=en) if needed.
4. Now add your Firebase credentials to the `index.html` file located in the `src` folder.

```
// TODO: Replace with your project's info.
var config = {
  apiKey: "<API_KEY>",
  authDomain: "<PROJECT_ID>.firebaseapp.com",
  databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
};
```

5. Build and deploy the library to your Firebase Hosting account.
```
npm run deploy -- --project=<PROJECT_ID>
```

6. Visit your site at: `https://<PROJECT_ID>.firebaseapp.com/<REMOTE_ID>`

**Comment by Gnanendra18** [comment]
Hi, Thanks for your reply. I have covered all the steps as mentioned above. But for the 6th point I hit the url without remote_id. What is remote_id. Where do we get it from.

**Comment by chriscox** [comment]
Ah ok. So just to clarify... this Remote Controller works only in conjunction with one of the native Remixer frameworks available ([iOS](https://github.com/material-foundation/material-remixer-ios), [Android](https://github.com/material-foundation/material-remixer-android), and [JavaScript](https://github.com/material-foundation/material-remixer-js)).  You essentially add one of those libraries to your app, define your variables, then trigger sharing from within the app. You will be provided a Remote ID only after you've enabled sharing from your app.  Once sharing is enabled, Remixer will send data to your remote controller host where you'll be able to update the variables remotely.

You can also visit the parent [Remixer](https://github.com/material-foundation/material-remixer) site with links to all of the repos as needed.

**Comment by Gnanendra18** [comment]
Ok got it. Thanks.

**Comment by chriscox** [comment]
Great thanks. Closing this issue.
