### ISSUE TITLE
Make alpha component in Color consistent with the other components

### ISSUE THREAD

**Issue by miguelandres** [material-foundation/material-remixer-remote-web#9]
Alpha is currently represented by a 0-1 floating point number when syncing, as discussed offline, please update to syncing a 0-255 integer for cross platform concerns.

Thanks

**Comment by chriscox** [comment]
Issue is being fixed in Javascript framework repo:
https://github.com/material-foundation/material-remixer-js/pull/79

**Comment by chriscox** [comment]
Fixed when updating to material remixer v.0.6.4 here in this commit: https://github.com/material-foundation/material-remixer-remote-web/commit/404ba8ed557ceacdde2d74432e3b2ffc3093011a
